{% set name = "tty-prompt" %}
{% set version = "0.20.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 5dc55f299c409ce4eaedd58f87ff51235673dc0b307225400e5e3b86bced6ba6

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
      && gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.5.5
  run:
    - ruby >=2.5.5
    - rb-necromancer >=0.5.0,<0.6
    - rb-pastel >=0.7.0,<0.8
    - rb-tty-reader >=0.6.0,<0.7

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: 'A beautiful and powerful interactive command line prompt with a robust API for getting and validating complex inputs.'
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/piotrmurach/tty-prompt

extra:
  recipe-maintainers:
    - sodre
    - rluria14
    - adbeda
