{% set name = "tty-prompt" %}
{% set version = "0.23.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: fcdbce905238993f27eecfdf67597a636bc839d92192f6a0eef22b8166449ec8

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby >=2.6.5,<2.7.0a0
    - rb-pastel >=0.8
    - rb-tty-reader >=0.7

test:
  commands:
    - ruby -r tty-prompt -e 'exit 0'

about:
  home: https://rubygems.org/gems/tty-prompt
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A beautiful and powerful interactive command line prompt with a robust API for getting and validating complex inputs.
  doc_url: https://www.rubydoc.info/gems/{tty-prompt
  dev_url: https://github.com/piotrmurach/tty-prompt

extra:
  recipe-maintainers:
    - sodre
    - mxr-conda
