travis:
  secure:
    BINSTAR_TOKEN: jVjLpdjLvxmaULUnXbzxsZtEll8ma3L+NrrX33UKN8aXftdbL66kPW1A6jUuh5a9uc+A65PDlxgWtCFzxLUq6r0SkvfHAUCh335s3yw7D2hZ8axdPoMOq8sThmspStoiv81PaZwtoK6DcuSsjB7Vh0iIwuJCzqjcves/Uvt/sRJQJcTspU71LTcOZxJfHzEqDA2u/CQDFR7i5OX6g4Th6BUAjw52J7vCYU7QNXp/fulXTCtbnop57OHGCgi3AlBCw7eK329IehEji+Gj9x5AzLjYwScXG4x67ZQoqIjdqE/PU7+GSqUDtDCy30R4KUBrKXVNKqFy+Wpd+WGBs8NIRoB71bKgAW4vz59bMLhdrBxs81+xRnJ9If7QeRAh7k1glfglN9yQzDNSH5uhvyDzFBVRSG8u1GeIPCqXLbJ5UMp75tLaowrtkNvUL1LQy5VKp8GqgXWquwmaP1RyeUH2X4AT84XwOfEVxwv0Pmi3zLUefyBB7B9IpiwHUTp2CrSJZUaLjluW86A5mdUPgIDtnuu5WSg1JCrDY65Nr5esdtzOJdZgOjtqnYTLlkYGjDKh9ZcsuZaz1fxAycXnxV2ByufwT9IZFoIxjfn66pOtsQMCK1qro5i3OGIYAqcc3SEqnNeH2T8pMl3tFKReYkFMn0b5tkjifT7wljr+yhF1Wfc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
